# fly.toml app configuration file generated for bsfaqbot on 2023-05-05T18:06:19+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "bsfaqbot"
kill_signal = "SIGINT"
kill_timeout = 5
primary_region = "lhr"
processes = []

[build]

[env]

[experimental]
  auto_rollback = false
